FROM haskell:8.0.1

# Create user
RUN useradd -ms /bin/bash wolf

USER wolf
WORKDIR /home/wolf

# Install GHC
RUN stack setup

# Add and Install Application Code
COPY . /home/wolf
RUN stack build

ENTRYPOINT sleep infinity
